title: Zachary's Website
email: zacharylopez@mail.weber.edu
description: >- # this means to ignore newlines until "baseurl:"
  My awesome website is about my and my best friend Alex. Not only is she
  a great friend but she is also my neice.
logo: "/assets/images/AlexWithMe.jpg"
baseurl: "/my-first-website-zlopez0" # the subpath of your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
